dataset_name: "affahrizain/jigsaw-toxic-comment"
dataset_split: "train" 
subset_size: 1000
model_name: "distilbert-base-uncased"
batch_size: 16
metrics:
  - "toxicity"
  - "bias"
output_path: "phase2_results.csv"
